### ISSUE TITLE
Warlock drain life spell channel causing divide by zero in ZPerl_ArcaneBar.lua

### ISSUE THREAD

**Issue by xartin** [Resike/Z-Perl#1]
Channeling drain live as a warlock causes zperl to also channel thousands of lua errors. see screenshot for more details.  
  
![wowscrnshot_071816_030852](https://cloud.githubusercontent.com/assets/20513061/16909283/57614554-4c97-11e6-8f8e-d4b79fd3c6da.jpg)

**Comment by Resike** [comment]
Thats intresting, either the server latency returns nil, or the cast start-end time. Will look into this.

**Comment by xartin** [comment]
cheers for that. it's reproducable every time drain life is cast. using destruction spec so not sure if that matters.  
  
Thanks much for doing what you do. blizzard's UI is literally cancer lol

**Comment by Resike** [comment]
Found the issue, will be fixed in the next version.
