### ISSUE TITLE
Ready Checks

### ISSUE THREAD

**Issue by Kyrgune** [Resike/Z-Perl#104]
I am not seeing the ready checks, not ready checks or the "?" for have not clicked either in the raid frames or party frames.

**Comment by Nersunea** [comment]
I have the same issue

**Comment by zeenk** [comment]
I assume Blizzard broke/changed something since it doesn't show on older zperl versions as well

**Comment by zeenk** [comment]
My friend helped me find a solution for this problem, @Resike (Sorry about the ping!)

Go into ZPerl.lua and replace line 3810 to 3824 with
```
function XPerl_Unit_UpdateReadyState(self)
    local status = conf.showReadyCheck and self.partyid and GetReadyCheckStatus(self.partyid)
    if (status) then
        self.statsFrame.ready:Show()
        if (status == "ready") then
            self.statsFrame.ready.check:SetAtlas(READY_CHECK_READY_TEXTURE)
        elseif (status == "waiting") then
            self.statsFrame.ready.check:SetAtlas(READY_CHECK_WAITING_TEXTURE)
        else -- "notready"
            self.statsFrame.ready.check:SetAtlas(READY_CHECK_NOT_READY_TEXTURE)
        end
    else
        self.statsFrame.ready:Hide()
    end
end
```
Then it will show again, basically just replace SetTexture with SetAtlas 😄 
![2023-12-22_22-34-46](https://github.com/Resike/Z-Perl/assets/68170439/8807afcf-c440-4880-a449-c5fe0a830edf)

**Comment by Kyrgune** [comment]
Very nice zeenk, thanks for the info!
