### ISSUE TITLE
SoD Durid Livebloom Rune Spell Lua Error

### ISSUE THREAD

**Issue by Oozanalp** [Resike/Z-Perl#106]
When I cast the lifebloom spell on myself, the following error occurs:

Message: ...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:820: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
Time: Wed Dec 20 18:44:59 2023
Count: 4
Stack: ...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:820: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
[string "@Interface/AddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:820: in function <...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:809>
[string "@Interface/AddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:969: in function <...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:967>
[string "@Interface/AddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:2724: in function `?'
[string "@Interface/AddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:3378: in function <...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:3376>

Locals: spellData = <table> {
 levels = <table> {
 }
 bomb = <table> {
 }
 coeff = 0.520000
 interval = 1
 ticks = 7
 averages = <table> {
 }
 dhCoeff = 0.343350
}
spellName = "Lifebloom"
spellID = 408124
spellRank = nil
average = nil
requiresLevel = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 12
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'requiresLevel' (a nil value)"
type = <function> defined =[C]:-1
min = <function> defined =[C]:-1
playerLevel = 12

**Comment by imfalliblek** [comment]
I have this same issue. 


Message: ...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:820: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
Time: Fri Dec 22 07:17:21 2023
Count: 1
Stack: ...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:820: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
[string "@Interface/AddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:820: in function <...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:809>
[string "@Interface/AddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:969: in function <...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:967>
[string "@Interface/AddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:2724: in function `?'
[string "@Interface/AddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:3378: in function <...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:3376>

Locals: spellData = <table> {
 levels = <table> {
 }
 bomb = <table> {
 }
 coeff = 0.520000
 interval = 1
 ticks = 7
 averages = <table> {
 }
 dhCoeff = 0.343350
}
spellName = "Lifebloom"
spellID = 408124
spellRank = nil
average = nil
requiresLevel = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 15
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'requiresLevel' (a nil value)"
type = <function> defined =[C]:-1
min = <function> defined =[C]:-1
playerLevel = 15

**Comment by ElegantSerr** [comment]
SoD Lifebloom rune is not implemented in the included LibHealComm, a bypass mentioned in the LibHealComm issues is to add the spellID 408124 to the LibHealComm "spellRankTableData", I added it to the end of the table in line 87.
```
local spellRankTableData = {
	[1] = { .... , 408124 },
```
The healing values will be off but it'll stop the error from popping up.
