### ISSUE TITLE
10.2.5 Lua error in ZPerl_PartyPet.lua

### ISSUE THREAD

**Issue by InvisiBilldotnet** [Resike/Z-Perl#110]
I (non-pet class) haven't noticed any problems per se, but this error pops up repeatedly.

4x ZPerl_PartyPet/ZPerl_PartyPet.lua:396: attempt to compare number with nil
[string "@ZPerl_PartyPet/ZPerl_PartyPet.lua"]:396: in function <ZPerl_PartyPet/ZPerl_PartyPet.lua:370>
[string "@ZPerl_PartyPet/ZPerl_PartyPet.lua"]:458: in function `XPerl_Party_Pet_UpdateDisplay'
[string "@ZPerl_PartyPet/ZPerl_PartyPet.lua"]:706: in function `func'
[string "@ZPerl_PartyPet/ZPerl_PartyPet.lua"]:607: in function <ZPerl_PartyPet/ZPerl_PartyPet.lua:567>

Locals:
self = XPerl_partypet2 {
 0 = <userdata>
 statsFrame = XPerl_partypet2statsFrame {
 }
 petmanamax = 0
 conf = <table> {
 }
 pethp = 0
 buffFrame = XPerl_partypet2buffFrame {
 }
 FlashFrames = <table> {
 }
 ownerid = "party2"
 highlight = XPerl_partypet2highlight {
 }
 debuffFrame = XPerl_partypet2debuffFrame {
 }
 petmana = 0
 nameFrame = XPerl_partypet2nameFrame {
 }
 pethpmax = 0
 partyid = "partypet2"
 buffSetup = <table> {
 }
}
partyid = "partypet2"
unitPower = 0
unitPowerMax = 1
(*temporary) = nil
(*temporary) = "partypet2"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
UnitPower = <function> defined =[C]:-1
UnitPowerMax = <function> defined =[C]:-1

**Comment by zeenk** [comment]
Another similar error 

```
1x ZPerl_Player/ZPerl_Player.lua:748: attempt to compare number with nil
[string "@ZPerl_Player/ZPerl_Player.lua"]:748: in function <ZPerl_Player/ZPerl_Player.lua:724>
[string "@ZPerl_Player/ZPerl_Player.lua"]:1789: in function `?'
[string "@ZPerl_Player/ZPerl_Player.lua"]:1000: in function <ZPerl_Player/ZPerl_Player.lua:990>

Locals:
self = XPerl_Player {
 0 = <userdata>
 portraitFrame = XPerl_PlayerportraitFrame {
 }
 nameFrame = XPerl_PlayernameFrame {
 }
 unit = "player"
 partyid = "player"
 hitIndicator = XPerl_PlayerhitIndicator {
 }
 statsFrame = XPerl_PlayerstatsFrame {
 }
 Power = 0
 doubleCheckAFK = 2
 conf = <table> {
 }
 groupFrame = XPerl_PlayergroupFrame {
 }
 FlashFrames = <table> {
 }
 state = Frame {
 }
 runes = XPerl_Runes {
 }
 classFrame = XPerl_PlayerclassFrame {
 }
 highlight = XPerl_Playerhighlight {
 }
 time = 0
 feedbackFontHeight = 30
 feedbackText = XPerl_PlayerhitIndicatortext {
 }
 levelFrame = XPerl_PlayerlevelFrame {
 }
}
mb = XPerl_PlayerstatsFramemanaBar {
 0 = <userdata>
 percent = XPerl_PlayerstatsFramemanaBarpercent {
 }
 tex = XPerl_PlayerstatsFramemanaBartex {
 }
 text = XPerl_PlayerstatsFramemanaBartext {
 }
 bg = XPerl_PlayerstatsFramemanaBarbg {
 }
 SetValue = <function> defined @ZPerl/ZPerl.lua:2693
}
pType = nil
playermana = 0
playermanamax = 0
percent = 0
(*temporary) = <function> defined @ZPerl/ZPerl.lua:1037
(*temporary) = XPerl_PlayerstatsFramemanaBartext {
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = nil
(*temporary) = "enUS"
(*temporary) = "attempt to compare number with nil"
UnitPower = <function> defined =[C]:-1
UnitPowerMax = <function> defined =[C]:-1
percD = "%.0f%%"
max = <function> defined =[C]:-1
pconf = <table> {
 partyNumber = 1
 debuffs = <table> {
 }
 portrait = 1
 scale = 0.900000
 castBar = <table> {
 }
 fullScreen = <table> {
 }
 dockRunes = 1
 level = 1
 size = <table> {
 }
 threat = 1
 portrait3D = 1
 pvpIcon = 1
 lockRunes = 1
 healerMode = <table> {
 }
 healprediction = 1
 showRunes = 1
 hotPrediction = 1
 threatMode = "portraitFrame"
 totems = <table> {
 }
 absorbs = 1
 values = 1
 buffs = <table> {
 }
 percent = 1
 classIcon = 1
}
playerClass = nil
```

**Comment by Rebel-Kat** [comment]
Also, getting this
