### ISSUE TITLE
10.2.5 ZPerl_Player.lua error

### ISSUE THREAD

**Issue by Zetaprime82** [Resike/Z-Perl#113]
2x ZPerl_Player/ZPerl_Player.lua:748: attempt to compare number with nil
[string "@ZPerl_Player/ZPerl_Player.lua"]:748: in function <ZPerl_Player/ZPerl_Player.lua:724>
[string "@ZPerl_Player/ZPerl_Player.lua"]:1789: in function `?'
[string "@ZPerl_Player/ZPerl_Player.lua"]:1000: in function <ZPerl_Player/ZPerl_Player.lua:990>

Locals:
self = XPerl_Player {
 0 = <userdata>
 portraitFrame = XPerl_PlayerportraitFrame {
 }
 nameFrame = XPerl_PlayernameFrame {
 }
 unit = "player"
 partyid = "player"
 hitIndicator = XPerl_PlayerhitIndicator {
 }
 statsFrame = XPerl_PlayerstatsFrame {
 }
 Power = 0
 doubleCheckAFK = 2
 groupFrame = XPerl_PlayergroupFrame {
 }
 FlashFrames = <table> {
 }
 state = Frame {
 }
 conf = <table> {
 }
 classFrame = XPerl_PlayerclassFrame {
 }
 highlight = XPerl_Playerhighlight {
 }
 time = 0
 feedbackFontHeight = 30
 feedbackText = XPerl_PlayerhitIndicatortext {
 }
 levelFrame = XPerl_PlayerlevelFrame {
 }
}
mb = XPerl_PlayerstatsFramemanaBar {
 0 = <userdata>
 percent = XPerl_PlayerstatsFramemanaBarpercent {
 }
 tex = XPerl_PlayerstatsFramemanaBartex {
 }
 text = XPerl_PlayerstatsFramemanaBartext {
 }
 bg = XPerl_PlayerstatsFramemanaBarbg {
 }
 SetValue = <function> defined @ZPerl/ZPerl.lua:2693
}
pType = nil
playermana = 0
playermanamax = 0
percent = 0
(*temporary) = <function> defined @ZPerl/ZPerl.lua:1037
(*temporary) = XPerl_PlayerstatsFramemanaBartext {
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = nil
(*temporary) = "enUS"
(*temporary) = "attempt to compare number with nil"
UnitPower = <function> defined =[C]:-1
UnitPowerMax = <function> defined =[C]:-1
percD = "%.0f%%"
max = <function> defined =[C]:-1
pconf = <table> {
 partyNumber = 1
 debuffs = <table> {
 }
 portrait = 1
 scale = 0.900000
 castBar = <table> {
 }
 fullScreen = <table> {
 }
 hitIndicator = 1
 dockRunes = 1
 level = 1
 size = <table> {
 }
 threat = 1
 portrait3D = 1
 pvpIcon = 1
 lockRunes = 1
 healprediction = 1
 totems = <table> {
 }
 showRunes = 1
 hotPrediction = 1
 threatMode = "portraitFrame"
 healerMode = <table> {
 }
 absorbs = 1
 values = 1
 buffs = <table> {
 }
 percent = 1
 classIcon = 1
}
playerClass = nil

**Comment by EniacR** [comment]
1x ZPerl_PartyPet/ZPerl_PartyPet.lua:396: attempt to compare number with nil
[string "@ZPerl_PartyPet/ZPerl_PartyPet.lua"]:396: in function <ZPerl_PartyPet/ZPerl_PartyPet.lua:370>
[string "@ZPerl_PartyPet/ZPerl_PartyPet.lua"]:458: in function `XPerl_Party_Pet_UpdateDisplay'
[string "@ZPerl_PartyPet/ZPerl_PartyPet.lua"]:702: in function `func'
[string "@ZPerl_PartyPet/ZPerl_PartyPet.lua"]:607: in function <ZPerl_PartyPet/ZPerl_PartyPet.lua:567>

Locals:
self = XPerl_partypet1 {
 statsFrame = XPerl_partypet1statsFrame {
 }
 highlight = XPerl_partypet1highlight {
 }
 conf = <table> {
 }
 pethp = 0
 petmanamax = 0
 buffFrame = XPerl_partypet1buffFrame {
 }
 FlashFrames = <table> {
 }
 0 = <userdata>
 petmana = 0
 ownerid = "party1"
 nameFrame = XPerl_partypet1nameFrame {
 }
 partyid = "partypet1"
 pethpmax = 0
 debuffFrame = XPerl_partypet1debuffFrame {
 }
 buffSetup = <table> {
 }
}
partyid = "partypet1"
unitPower = 0
unitPowerMax = 1
(*temporary) = nil
(*temporary) = "partypet1"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
UnitPower = <function> defined =[C]:-1
UnitPowerMax = <function> defined =[C]:-1
