### ISSUE TITLE
Mana percentage display issue

### ISSUE THREAD

**Issue by BelziBhaal** [Resike/Z-Perl#114]
Hi,

Since the update, I have noticed that the unitframes shows the total mana next to the bar instead of the percentage. I cannot find a way to change this back. Screenshot attached.
![WoWScrnShot_011924_210522](https://github.com/Resike/Z-Perl/assets/45730242/07affd28-7c6e-4431-b636-89e49d8ea17d)

**Comment by Resike** [comment]
Fixed with next release.
