### ISSUE TITLE
Blizzard Combo Points Appearing Up Top When Not Enabled.

### ISSUE THREAD

**Issue by kmyth19** [Resike/Z-Perl#116]
I am using Z-Perl-7.1.8-Classic

If you move the target to no longer be up top, unselect the options for using blizzard combo, using combo bar, or using combo indicator, the original blizzard combo buttons will display at the top where the original blizzard target was located.

I have fixed this locally by adding the following to ZPerl_Target.lua > XPerl_Target_OnLoad at lines 191-193

	if not tconf.combo.enable and not tconf.comboindicator.enable and not tconf.combo.blizzard then 
		XPerl_BlizzFrameDisable(ComboFrame)
	end

I have tested this and the blizzard combo values where the original target was located no longer appear.  I have also verified that each of the individual replacement combo point options also works with this code.  I can enable / disable the options and they will function correctly without displaying the erroneous combo points on the original target location.

Feel free to use or not use.

**Comment by Resike** [comment]
In think you might have another addon that tries to move/show/reparent that ComboFrame/ComboPoints since I can't reproduce the issue. Is this also happening for you with every other then "ZPerl" addons disabled?

**Comment by kmyth19** [comment]
Adding a screen grab.  This was a fresh classic character with only zperl enabled.  I have none of the combo point options selected.  Blizzard's Combo Points, Display Combo Point Bar, and Display Combo Point Indicator are all disabled.
![ZPerl Combo Img](https://github.com/Resike/Z-Perl/assets/157192085/b9a35f48-8531-404b-ae8a-16c73425aed9)

**Comment by Resike** [comment]
Which Classic is this Wrath or Vanilla?

**Comment by kmyth19** [comment]
Season of Discovery.

**Comment by kmyth19** [comment]
And to be fair, I am not entirely sure this is a bug so much as a quirk.  If I have none of them selected, the combo points have to display somewhere for a rogue so the default combo points make sense.  So I don't know if this should be a different option altogether for "don't use any combo points" to completely disable ComboFrame otherwise use what is displayed in my image.

The idea being if I am using a different addon for combo points and don't want to see the default or use any of ZPerl's options.

**Comment by Resike** [comment]
I'll look into it, something must be different on Classic since this is not happening on Retail.

**Comment by Resike** [comment]
I still can't seem to reproduce this, if you have every combo disabled than no combo points should show up at all. The addon also just reusing the default combo points so I'm not sure how could this be true: `I have also verified that each of the individual replacement combo point options also works with this code.`

Are these combo points also visible when you don't have a target?
Are they getting updated properly or just stuck at 1 combo?

**Comment by kmyth19** [comment]
They are showing up and updating at the correct times.  No target, no combos.  No points, will show none, update to 1 etc.  

Honestly, I am fine with just updating the code with every update.  I just figured I would share.  This isn't a new thing.  I just finally decided to fix it locally lol.  No need to pull your hair out to dig it out :)

**Comment by Resike** [comment]
I made some changes that might fix it in the next version `7.1.9`.

**Comment by kmyth19** [comment]
Excellent!  Thank you!

**Comment by Resike** [comment]
Let me know if it works or not.

**Comment by kmyth19** [comment]
Update.  That worked!  I appreciate you fixing it!  Thanks!
