### ISSUE TITLE
Raid frames 

### ISSUE THREAD

**Issue by Rivertrent** [Resike/Z-Perl#117]
Just wondering how to hide icons that pop on the raid frames.  I have the raid frames closed always but i keep getting the icons over where the frames would be just above the chat box in the screenshot
![Defile showing on disabled raid frames](https://github.com/Resike/Z-Perl/assets/124846467/98f2fbb1-31a7-49af-b3ae-58a850b28c11)

**Comment by Resike** [comment]
Will try to fix it with the next version.
