### ISSUE TITLE
Rogue Combo Points in ZPerl-7.1.9-Wrath

### ISSUE THREAD

**Issue by DocDred** [Resike/Z-Perl#118]
In version 7.1.9-Wrath, Rogue combo points no longer appear to update properly when using Display Combo Point Indicator. I reverted back to version 7.1.7-Wrath where they work properly.

**Comment by DocDred** [comment]
They also appear to still work correctly in version 7.1.8-Wrath

**Comment by Resike** [comment]
Will look into it, are the other combo point indicators working on 7.1.9?

**Comment by DocDred** [comment]
The blizzard ones didn't appear to be but I'd have to look again.

**Comment by DocDred** [comment]
When showing "Blizzard's Combo Points" and Display Combo Point Indicator, the Blizzard dots appear to update as expected but the Combo Point box is not in sync with the dots. I've also used BasicComboPoints to compare both the blizz dots and combo point box and only the dots and BasicComboPoints are in sync with version 7.1.9.  This isn't an issue with 7.1.8 r919 or earlier that I can see.

**Comment by Resike** [comment]
Should be fixed with next release. Let me know if it still doesn't work.

**Comment by DocDred** [comment]
Will do, thank you very much :)

**Comment by DocDred** [comment]
7.2.0 appears to be working as expected. Thank you for the bug fix!
