### ISSUE TITLE
Casting bars not visible

### ISSUE THREAD

**Issue by Erunax** [Resike/Z-Perl#119]
The cast bar option is enabled for all my frames including "Party", "Target", "Pet" and "Raid", however the only cast bar that appears is for the "Player" frame. 

Could you help me to enable it to be able to see the cast bars for my targets and party members.

**Comment by xeropresence** [comment]
Noticed this as well on sod, party frames aren't getting castbars.

**Comment by xeropresence** [comment]
Looks like this might be an issue with LibClassicCasterino, if i disable the code that loads the functions from LibClassicCasterino party cast bars start working

**Comment by xeropresence** [comment]
So pretty interesting....

Partied up with 1 other person and had them cast hearthstone

With LCC enabled
No party cast bar
Target castbar appears
Have them hit escape
Nothing changes with party frame
Target cast bar keeps going for the full duration

Challenge them to a duel
With LCC enabled
Party castbar appears
Target castbar appears
Have them hit escape
Nothing changes with party frame
Party castbar stops
Target castbar stops

With LCC disabled
Party castbar appears
Target castbar appears
Have them hit escape
Nothing changes with party frame
Party castbar stops
Target castbar stops


So it seems like there is an issue with LCC and non-hostile members

**Comment by Resike** [comment]
Should be fixed with next release.
