### ISSUE TITLE
Buffs are Not Visible on my Nameplate

### ISSUE THREAD

**Issue by Derpadap** [Resike/Z-Perl#121]
Date: 2024-02-06 14:33:09
ID: 1
Error occured in: Global
Count: 1
Message: Interface/FrameXML/SecureGroupHeaders.lua line 1050:
   attempt to index local 'auraData' (a nil value)
Debug:
   [string "@Interface/FrameXML/SecureGroupHeaders.lua"]:1050:
      Interface/FrameXML/SecureGroupHeaders.lua:961
   [string "=[C]"]: Show()
   [string "@Interface/AddOns/ZPerl_PlayerBuffs/ZPerl_PlayerBuffs.lua"]:152: XPerl_Player_BuffSetup()
   [string "@Interface/AddOns/ZPerl_PlayerBuffs/ZPerl_PlayerBuffs.lua"]:200:
      ...rface/AddOns/ZPerl_PlayerBuffs/ZPerl_PlayerBuffs.lua:191
   [string "=[C]"]: ?
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:201: XPerl_pcall()
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:779:
      Interface/AddOns/ZPerl/ZPerl_Init.lua:761
   [string "=[C]"]: ?
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:201: XPerl_pcall()
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:496: ZPerl_Init()
   [string "@Interface/AddOns/ZPerl/ZPerl_Globals.lua"]:506:
      Interface/AddOns/ZPerl/ZPerl_Globals.lua:505
   [string "@Interface/AddOns/ZPerl/ZPerl_Globals.lua"]:620:
      Interface/AddOns/ZPerl/ZPerl_Globals.lua:591
Locals:
self = XPerl_PlayerbuffFrame {
 0 = <userdata>
 BuffFrameFlashState = 1
 BuffFrameFlashTime = 0
 BuffFrameUpdateTime = 0
 BuffAlphaValue = 1
}
filter = "HELPFUL"
groupBy = nil
unit = "player"
includeWeapons = 1
consolidateTo = nil
consolidateDuration = nil
consolidateThreshold = nil
consolidateFraction = nil
sortDirection = nil
separateOwn = 1
sortMethod = <function> defined @Interface/FrameXML/SecureGroupHeaders.lua:916
time = 3974.007000
consolidateTable = nil
weaponPosition = 1
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "HELPFUL"
 HELPFUL = 1
}
(for control) = 1
filterIndex = 1
fullFilter = "HELPFUL"
i = 1
aura = <table> {
}
_ = nil
duration = nil
auraData = nil
(*temporary) = nil
(*temporary) = "player"
(*temporary) = 1
(*temporary) = "HELPFUL"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'auraData' (a nil value)"
tonumber = <function> defined =[C]:-1
sorters = <table> {
 INDEX = <table> {
 }
 TIME = <table> {
 }
 NAME = <table> {
 }
 EXPIRES = <table> {
 }
}
wipe = <function> defined =[C]:-1
tokenTable = <table> {
}
sortingTable = <table> {
}
groupingTable = <table> {
 1 = "HELPFUL"
 HELPFUL = 1
}
stripRAID = <function> defined @Interface/FrameXML/SecureGroupHeaders.lua:881
ipairs = <function> defined =[C]:-1
freshTable = <function> defined @Interface/FrameXML/SecureGroupHeaders.lua:889
max = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
releaseTable = <function> defined @Interface/FrameXML/SecureGroupHeaders.lua:894
configureAuras = <function> defined @Interface/FrameXML/SecureGroupHeaders.lua:735
tremove = <function> defined =[C]:-1

AddOns:
  Swatter, v3.4.6977 (SwimmingSeadragon)
  Atlas, vv1.52.08
  AtlasClassicWoW, vv1.52.05
  AucAdvanced, v3.4.6952 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v10.2.18
  BeanCounter, v3.4.6983 (SwimmingSeadragon)
  ChatCopyPaste, v1.19
  ConsolePort, v2.7.27
  ConsolePortBar, v
  ConsolePortCursor, v
  ConsolePortMenu, v
  ConsolePortWorld, v
  DBMCore, vf4d2083
  DBMStatusBarTimers, vf4d2083
  DBMVPVEM, v9705bdd
  Details, v#Details.20240204.12256.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6979 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6917 (SwimmingSeadragon)
  ErrorFilter, vv3.8
  GatherMate2, v1.47.2-classic
  Informant, v3.4.6980 (SwimmingSeadragon)
  Plater, vPlater-v575-Classic
  Questie, v9.3.3
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  ZPerl, v7.2.0
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib v1.15.1.53181(US) <enUS>
  (ck=61d)

I hope this can be helpful in solving this issue

**Comment by Resike** [comment]
Sadly I don't think I can't fix that, blizzard messed up their own code and they need to fix it.
