### ISSUE TITLE
Water bug macOS

### ISSUE THREAD

**Issue by qetuo15** [Resike/Z-Perl#124]
In WoW Classic SOD the water flashing all the time. 
Happens only on macOS!
Any suggestions? Anyone else had this issue?

Video:
https://youtu.be/BWhr7n88U4Y

**Comment by Resike** [comment]
I don't think this has to do anything with addon, it's probably a classic or mac bug in the game itself.

**Comment by qetuo15** [comment]
If the add-on disabled everything is fine as in the video. 
I also tried to disable component of the add-on and the following happened: 
Player frame disabled: everything is good till I target something or join a group (when anything from the add-on is visible) The problem up only when something displayed what modified by the add-on. If the add-on enabled but press alt+z everything is good too.

**Comment by Resike** [comment]
It could be the 3D models that's created by the addon on the frames, you could try to disable 3D portraits or disable the portrait frames entirely and test it like that.

**Comment by qetuo15** [comment]
Disable the 3D portrait solved the problem, huge thank you!

**Comment by Resike** [comment]
You probably gonna need to report this issue to Blizzard with your MAC version and stuff that 3D models drawn by addons cause this issue.
