### ISSUE TITLE
Hostile unit buffs no longer showing after 7.2.3 on classic

### ISSUE THREAD

**Issue by xeropresence** [Resike/Z-Perl#125]
Looks like removing [LibClassicDurations](https://github.com/rgd87/LibClassicDurations) broke seeing buffs like renew, iron will, and arcane bubble from the mobs in sm:library, I assume this effects other npcs as well

**Comment by Resike** [comment]
That's true but on Classic you are no supposed to see enemy buffs unless `Detect Magic` is applied. Still considering if I should add it back but only for the target/focus frames.
