### ISSUE TITLE
Druid`s manabar

### ISSUE THREAD

**Issue by Seipro** [Resike/Z-Perl#131]
![изображение_2024-04-08_205811758](https://github.com/Resike/Z-Perl/assets/166434234/4ed8d46c-c312-444a-823a-9612d2fe103a)
![изображение_2024-04-08_205835705](https://github.com/Resike/Z-Perl/assets/166434234/6b656971-1cbd-4082-a4e4-dca9bb572a43)
Z-Perl Unit Frames. 7.2.3-Classic.zip on CurseForge.
Every time after shapeshift to the cat form, the mana bar looks like in the first screenshot (thin). In the second screenshot, how it should look (wide). The problem is observed only with the cat. It works properly with the bear.

**Comment by Resike** [comment]
Sadly I don't think I can fix this. Low level druids can have their shapeshift forms in different places then the max level ones, based on what forms are they learned/available to them.
