### ISSUE TITLE
Add Cataclysm classic support

### ISSUE THREAD

**Issue by glajchs** [Resike/Z-Perl#134]
I was able to get it working locally by doing 2 things. First replacing all the "IsWrathClassic" checks with an "is wrath or cata" check and using it everywhere. Second by commenting out 3 spellids no longer in the game in the buff tracker list.

Fist for the wrath/cata checks. I did something like this:
```local IsWrathClassic = WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC
local IsWrathOrCata = (WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC) or (WOW_PROJECT_ID == WOW_PROJECT_CATACLYSM_CLASSIC)
```
Then I updated all usages to IsWrathOrCata instead of IsWrathClassic

Second, in ZPerl.lua, at about lines 2243, there are 3 spellids I commented out. Aspect of the Monkey, Seal of Command, and Seal of Wisdom.

After all of that it seemed to load and work well enough (initial testing)

**Comment by Aenimma** [comment]
Thanks for this, mine zperl is still very broken, showing blank name plates, I think Target and Target or Target etc.

**Comment by PowershellNinja** [comment]
Thanks @glajchs!
With your changes most of the errors are gone and the UI works mostly well!

**Comment by starek4** [comment]
Created a PR for that: https://github.com/Resike/Z-Perl/pull/137/files

Thanks @glajchs
