### ISSUE TITLE
CATA Classic Issues

### ISSUE THREAD

**Issue by Aenimma** [Resike/Z-Perl#135]
Hello I am getting the following error when loading into the game

Date: 2024-05-01 16:12:45
ID: 5
Error occured in: Global
Count: 1
Message: XPerl_TargetTarget:RegisterUnitEvent(): Attempt to register unknown event "UNIT_ABSORB_AMOUNT_CHANGED"
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: RegisterUnitEvent()
   [string "@Interface/AddOns/ZPerl/ZPerl.lua"]:4367: XPerl_Register_Prediction()
   [string "@Interface/AddOns/ZPerl_TargetTarget/ZPerl_TargetTarget.lua"]:92:
      ...ace/AddOns/ZPerl_TargetTarget/ZPerl_TargetTarget.lua:68
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by Aenimma** [comment]
This is a second error I am getting when loading into the game.

Date: 2024-05-01 16:12:47
ID: 9
Error occured in: Global
Count: 1
Message: XPerl_Player:RegisterUnitEvent(): Attempt to register unknown event "UNIT_ABSORB_AMOUNT_CHANGED"
Debug:
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:207: XPerl_pcall()
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:779:
      Interface/AddOns/ZPerl/ZPerl_Init.lua:761
   [string "=[C]"]: ?
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:201: XPerl_pcall()
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:496: ZPerl_Init()
   [string "@Interface/AddOns/ZPerl/ZPerl_Globals.lua"]:506:
      Interface/AddOns/ZPerl/ZPerl_Globals.lua:505
   [string "@Interface/AddOns/ZPerl/ZPerl_Globals.lua"]:620:
      Interface/AddOns/ZPerl/ZPerl_Globals.lua:591
Locals:
success = false
error = "XPerl_Player:RegisterUnitEvent(): Attempt to register unknown event "UNIT_ABSORB_AMOUNT_CHANGED""
pcall = <function> defined =[C]:-1
errorCount = 1
doneOptions = nil
geterrorhandler = <function> defined =[C]:-1

**Comment by Aenimma** [comment]
Date: 2024-05-01 16:12:47
ID: 10
Error occured in: Global
Count: 1
Message: XPerl_Player_Pet:RegisterUnitEvent(): Attempt to register unknown event "UNIT_ABSORB_AMOUNT_CHANGED"
Debug:
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:207: XPerl_pcall()
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:779:
      Interface/AddOns/ZPerl/ZPerl_Init.lua:761
   [string "=[C]"]: ?
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:201: XPerl_pcall()
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:496: ZPerl_Init()
   [string "@Interface/AddOns/ZPerl/ZPerl_Globals.lua"]:506:
      Interface/AddOns/ZPerl/ZPerl_Globals.lua:505
   [string "@Interface/AddOns/ZPerl/ZPerl_Globals.lua"]:620:
      Interface/AddOns/ZPerl/ZPerl_Globals.lua:591
Locals:
success = false
error = "XPerl_Player_Pet:RegisterUnitEvent(): Attempt to register unknown event "UNIT_ABSORB_AMOUNT_CHANGED""
pcall = <function> defined =[C]:-1
errorCount = 2
doneOptions = nil
geterrorhandler = <function> defined =[C]:-1

**Comment by Aenimma** [comment]
Date: 2024-05-01 16:12:47
ID: 11
Error occured in: Global
Count: 1
Message: XPerl_Target:RegisterUnitEvent(): Attempt to register unknown event "UNIT_ABSORB_AMOUNT_CHANGED"
Debug:
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:207: XPerl_pcall()
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:779:
      Interface/AddOns/ZPerl/ZPerl_Init.lua:761
   [string "=[C]"]: ?
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:201: XPerl_pcall()
   [string "@Interface/AddOns/ZPerl/ZPerl_Init.lua"]:496: ZPerl_Init()
   [string "@Interface/AddOns/ZPerl/ZPerl_Globals.lua"]:506:
      Interface/AddOns/ZPerl/ZPerl_Globals.lua:505
   [string "@Interface/AddOns/ZPerl/ZPerl_Globals.lua"]:620:
      Interface/AddOns/ZPerl/ZPerl_Globals.lua:591
Locals:
success = false
error = "XPerl_Target:RegisterUnitEvent(): Attempt to register unknown event "UNIT_ABSORB_AMOUNT_CHANGED""
pcall = <function> defined =[C]:-1
errorCount = 3
doneOptions = nil
geterrorhandler = <function> defined =[C]:-1

**Comment by Tdqss** [comment]
This is how I fixed it for me until there is an official release
change in ZPerl.lua and Zperl_Raid.lua WOW_PROJECT_WRATH_CLASSIC to WOW_PROJECT_CATACLYSM_CLASSIC
and comment out in ZPerl.lua line 2336 (Aspect of the Monkey) and Seal of Command, Wisdom, Light a little below

**Comment by starek4** [comment]
PR for fixing those here: https://github.com/Resike/Z-Perl/pull/137/files

**Comment by Hysterea** [comment]
Tdqss, you are a freakin god bro. This worked like a charm. You saved my UI, many many thanks! I
