### ISSUE TITLE
Ready check not showing who's ready issue DF Season 4 

### ISSUE THREAD

**Issue by SteveoJP** [Resike/Z-Perl#136]
Been using this addon for so long. Only issue I am having at the moment is that ready check is not showing who's ready. I can confirm I have checked the settings and made sure it's selected in the settings. Any ideas?

Thanks

**Comment by Resike** [comment]
Gonna be fixed with the next version.

**Comment by SteveoJP** [comment]
Thank you for your reply. I am happy it's getting fixed. I love this addon been using it for many years!
