### ISSUE TITLE
Eclipse Bar -  Moonkin Druids Missing

### ISSUE THREAD

**Issue by kolproductions** [Resike/Z-Perl#139]
Recently installed the update for Z-Perl Unitframes for Cata --   Very much appreciated.   

The only issue which I have found currently,  there's no bar for Eclipse State for Boomkins.   
[ Lunar Energy <<<--------| -------->>> Solar Energy ]

**Comment by Resike** [comment]
Yeah gonna look into that next.

**Comment by Vitium92** [comment]
To expand on this topic, not only affects Druids, it also affects the rest of the classes with special bars (Paladins, etc.) even though the option for special bars is enabled on the config.

**Comment by Tdqss** [comment]
'EclipseBarFrame' is the name in the new Cata game files, might work like the holy power fix
