### ISSUE TITLE
Raid Frames show 100.1% instead of 100%

### ISSUE THREAD

**Issue by boktai1000** [Resike/Z-Perl#14]
I noticed on my raid frames, it shows everyone with 100.1% instead of 100%

Is there a way to fix this? If not consider this a bug report. I could also disable tracking based on decimal percentages if that's somewhere, please let me know. Thank you!

![image](https://user-images.githubusercontent.com/9054563/129423819-207b0b02-8995-4d3c-9e73-f566c8fc00ed.png)

**Comment by Resike** [comment]
Fixed
