### ISSUE TITLE
paladin holy power issues

### ISSUE THREAD

**Issue by toxicshot15** [Resike/Z-Perl#140]
I have updated to the current zperl UI and i seem to have an issue with it showing paladins holy power.
either in holy or ret spec it does not show up.

any suggestions? 
thanks

**Comment by cconolly** [comment]
Doesn't show up warlocks soulshards as well ...

**Comment by Tdqss** [comment]
replace these 2 functions in ZPerl_Player/ZPerl_Player.lua
(moving not implemented)

```
-- XPerl_Player_InitWarlock
function XPerl_Player_InitWarlock(self, playerClass)
	if (not (IsRetail or IsCataClassic)) or playerClass ~= "WARLOCK" --[[or self.runes]] then
		return
	end

		if (not ShardBarFrame or ShardBarFrame:GetParent() ~= PlayerFrame or not ShardBarFrame:IsShown() or not pconf.showRunes) then
			-- Only hijack runes if not already done so by another mod
			--return
		end
	    
		self.runes = CreateFrame("Frame", "XPerl_Runes", self)
		self.runes:SetPoint("TOPLEFT", self.portraitFrame, "BOTTOMLEFT", 0, 2)
		self.runes:SetPoint("BOTTOMRIGHT", self.statsFrame, "BOTTOMRIGHT", 0, -30)
		ShardBarFrame:SetPoint("TOPLEFT", self.statsFrame, "BOTTOMLEFT", 20, 1)
		self.runes.unit = "player"
		ShardBarFrame:SetParent(self.runes)
		--MakeMoveable(self)
end

-- XPerl_Player_InitPaladin
function XPerl_Player_InitPaladin(self, playerClass)
	if (not (IsRetail or IsCataClassic)) or playerClass ~= "PALADIN" --[[or self.runes]] then
		return
	end

	if (not PaladinPowerBar or PaladinPowerBar:GetParent() ~= PlayerFrame or not PaladinPowerBar:IsShown() or not pconf.showRunes) then
		-- Only hijack runes if not already done so by another mod
		return
	end

	self.runes = CreateFrame("Frame", "XPerl_Runes", self)
	self.runes:SetPoint("TOPLEFT", self.portraitFrame, "BOTTOMLEFT", 0, 2)
	self.runes:SetPoint("BOTTOMRIGHT", self.statsFrame, "BOTTOMRIGHT", 0, -30)
	PaladinPowerBar:SetPoint("TOPLEFT", self.statsFrame, "BOTTOMLEFT", 0, 6)
	self.runes.unit = "player"
	PaladinPowerBar:SetParent(self.runes)--XPerl_Player)
	--MakeMoveable(self)

end
```

**Comment by cconolly** [comment]
> replace these 2 functions in ZPerl_Player/ZPerl_Player.lua (moving not implemented)
> 
> ```
> -- XPerl_Player_InitWarlock
> function XPerl_Player_InitWarlock(self, playerClass)
> 	if (not (IsRetail or IsCataClassic)) or playerClass ~= "WARLOCK" --[[or self.runes]] then
> 		return
> 	end
> 
> 		if (not ShardBarFrame or ShardBarFrame:GetParent() ~= PlayerFrame or not ShardBarFrame:IsShown() or not pconf.showRunes) then
> 			-- Only hijack runes if not already done so by another mod
> 			--return
> 		end
> 	    
> 		self.runes = CreateFrame("Frame", "XPerl_Runes", self)
> 		self.runes:SetPoint("TOPLEFT", self.portraitFrame, "BOTTOMLEFT", 0, 2)
> 		self.runes:SetPoint("BOTTOMRIGHT", self.statsFrame, "BOTTOMRIGHT", 0, -30)
> 		ShardBarFrame:SetPoint("TOPLEFT", self.statsFrame, "BOTTOMLEFT", 20, 1)
> 		self.runes.unit = "player"
> 		ShardBarFrame:SetParent(self.runes)
> 		--MakeMoveable(self)
> end
> 
> -- XPerl_Player_InitPaladin
> function XPerl_Player_InitPaladin(self, playerClass)
> 	if (not (IsRetail or IsCataClassic)) or playerClass ~= "PALADIN" --[[or self.runes]] then
> 		return
> 	end
> 
> 	if (not PaladinPowerBar or PaladinPowerBar:GetParent() ~= PlayerFrame or not PaladinPowerBar:IsShown() or not pconf.showRunes) then
> 		-- Only hijack runes if not already done so by another mod
> 		return
> 	end
> 
> 	self.runes = CreateFrame("Frame", "XPerl_Runes", self)
> 	self.runes:SetPoint("TOPLEFT", self.portraitFrame, "BOTTOMLEFT", 0, 2)
> 	self.runes:SetPoint("BOTTOMRIGHT", self.statsFrame, "BOTTOMRIGHT", 0, -30)
> 	PaladinPowerBar:SetPoint("TOPLEFT", self.statsFrame, "BOTTOMLEFT", 0, 6)
> 	self.runes.unit = "player"
> 	PaladinPowerBar:SetParent(self.runes)--XPerl_Player)
> 	--MakeMoveable(self)
> 
> end
> ```

It didn't work and even broke interface.

**Comment by Tdqss** [comment]
Are you on the latest ZPerl? Is there already any 'IsCataClassic' in the file?
Could you copy the first error about ZPerl? step back if there are multiple

**Comment by Resike** [comment]
I'll fix special powers today.
