### ISSUE TITLE
Massive Lua errors with cata pre patch

### ISSUE THREAD

**Issue by Gwills76** [Resike/Z-Perl#141]
10x ...ddOns/ZPerl/Libs/LibHealComm-4.0-117/LibHealComm-4.0.lua:1538: table index is nil
[string "@ZPerl/Libs/LibHealComm-4.0-117/LibHealComm-4.0.lua"]:1538: in function <...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:1482>
[string "@ZPerl/Libs/LibHealComm-4.0-117/LibHealComm-4.0.lua"]:3455: in function `OnInitialize'
[string "@ZPerl/Libs/LibHealComm-4.0-117/LibHealComm-4.0.lua"]:3595: in function `?'
[string "@ZPerl/Libs/LibHealComm-4.0-117/LibHealComm-4.0.lua"]:3574: in function <...ddOns/ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:3570>

Locals:
Renew = "Renew"
GreaterHeal = "Greater Heal"
PrayerofHealing = "Prayer of Healing"
FlashHeal = "Flash Heal"
Heal = "Heal"
LesserHeal = "Heal"
SpiritualHealing = "Tome of Light"
ImprovedRenew = "Improved Renew"
GreaterHealHot = "Greater Heal"
DispelMagic = "Dispel Magic"
BindingHeal = "Binding Heal"
EmpoweredHealing = "Empowered Healing"
Renewal = "37563"
Penance = "Penance"
Grace = "Grace"
BlessedResilience = "Blessed Resilience"
FocusedPower = "Focused Power"
DivineProvidence = "Divine Providence"
EmpoweredRenew = "Divine Touch"
TwinDisciplines = "Twin Disciplines"
(*temporary) = <table> {
 Greater Heal = <table> {
 }
 Flash Heal = <table> {
 }
}
(*temporary) = <table> {
 levels = <table> {
 }
 averages = <table> {
 }
 coeff = 0.857143
}
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
}
(*temporary) = <table> {
 1 = 318
 2 = 320.500000
 3 = 322.500000
 4 = 325.500000
 5 = 327.500000
 6 = 330
}
(*temporary) = <table> {
 1 = 460
 2 = 463.500000
 3 = 466.500000
 4 = 469.500000
 5 = 472.500000
 6 = 476
}
(*temporary) = <table> {
 1 = 604
 2 = 608
 3 = 612
 4 = 616
 5 = 620
 6 = 624
}
(*temporary) = <table> {
 1 = 758
 2 = 762.500000
 3 = 767
 4 = 771.500000
 5 = 776
 6 = 780.500000
}
(*temporary) = 758
(*temporary) = 762.500000
(*temporary) = 767
(*temporary) = 771.500000
(*temporary) = 776
(*temporary) = 780.500000
(*temporary) = 734
(*temporary) = 827
(*temporary) = 780.500000
(*temporary) = 4621
(*temporary) = 4300.500000
(*temporary) = 3722.500000
(*temporary) = 1618
(*temporary) = 1872
(*temporary) = "table index is nil"
GetSpellInfo = <function> defined =[C]:-1
hotData = <table> {
 Renew = <table> {
 }
 Greater Heal = <table> {
 }
 37563 = <table> {
 }
}
spellData = <table> {
 Greater Heal = <table> {
 }
 Flash Heal = <table> {
 }
}
avg = <function> defined @ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:834
isWrath = false
isTBC = false
isSoD = false
generateSODAverages = <function> defined @ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:890
talentData = <table> {
}
itemSetsData = <table> {
}
AuraHandler = nil
select = <function> defined =[C]:-1
unitHasAura = <function> defined @ZPerl/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:793
GetHealTargets = nil
playerGUID = "Player-4728-0559720B"
format = <function> defined =[C]:-1
compressGUID = <table> {
}
UnitGUID = <function> defined =[C]:-1
guidToGroup = <table> {
}
pairs = <function> defined =[C]:-1
guidToUnit = <table> {
 Player-4728-0559720B = "player"
}
isClassicEra = false
InCombatLockdown = <function> defined =[C]:-1
IsSpellInRange = <function> defined =[C]:-1
CheckInteractDistance = <function> defined =[C]:-1
UnitIsVisible = <function> defined =[C]:-1
UnitHasVehicleUI = <function> defined =[C]:-1
CalculateHotHealing = nil
SpellIDToRank = <table> {
 23569 = 6
 55458 = 6
 6064 = 4
 25222 = 12
 51945 = 1
 6074 = 2
 6076 = 4
 6078 = 6
 10623 = 3
 425269 = 2
 425270 = 3
 639 = 2
 25422 = 4
 7651 = 4
 48784 = 8
 55459 = 7
 1026 = 4
 425274 = 7
 2050 = 1
 2052 = 2
 2053 = 3
 2054 = 1
 2055 = 2
 425276 = 9
 2060 = 1
 2061 = 1
 45543 = 13
 774 = 1
 647 = 3
 51803 = 16
 27219 = 7
 48785 = 9
 27259 = 8
 10328 = 7
 1042 = 5
 9841 = 10
 5186 = 2
 5188 = 4
 3111 = 2
 2090 = 4
 2091 = 5
 412510 = 1
 3627 = 6
 10396 = 9
 9889 = 10
 10915 = 5
 25391 = 11
 10927 = 7
 25423 = 5
 8903 = 7
 26980 = 10
 10963 = 2
 913 = 4
 1058 = 2
 52986 = 2
 8939 = 3
 13542 = 5
 48451 = 3
 9474 = 4
 1064 = 1
 331 = 1
 48068 = 14
 3661 = 3
 3662 = 4
 332 = 2
 27220 = 8
 52987 = 3
 50464 = 1
 136 = 1
 32546 = 1
 3698 = 2
 3699 = 3
 3700 = 4
 26981 = 12
 401417 = 1
 7927 = 6
 547 = 3
 19939 = 2
 48070 = 10
 9758 = 8
 436937 = 1
 37563 = 1
 10329 = 8
 25233 = 8
 51999 = 5
 48438 = 1
 939 = 5
 25297 = 11
 9858 = 9
 9862 = 3
 436942 = 5
 33763 = 1
 436943 = 6
 48119 = 2
 10916 = 6
 436944 = 7
 10928 = 8
 436945 = 8
 26982 = 13
 436946 = 9
 689 = 1
 10964 = 3
 27030 = 11
 8936 = 1
 8940 = 4
 13543 = 6
 3267 = 3
 3268 = 4
 19940 = 3
 48072 = 7
 48120 = 3
 415236 = 1
 6063 = 3
 6075 = 3
 6077 = 5
 48440 = 14
 61295

**Comment by Resike** [comment]
Will be removing LibHealComm for Cata until it's properly updated.
