### ISSUE TITLE
Z-Perl not working

### ISSUE THREAD

**Issue by mechanix4488** [Resike/Z-Perl#163]
The addon is not working at all.  When I try to go into the options, it says Failed to load Z-Perl Options (MISSING).

![Z-Perl Error](https://github.com/user-attachments/assets/18bc937e-7a6f-4a53-bb2d-85752c6aa205)

**Comment by Thorgs** [comment]
I have the same issue. All Z-Perl Modules are missing but one!

<img width="454" alt="perl missing" src="https://github.com/user-attachments/assets/5ab08210-19ed-4786-b5bb-78c8211e38bb">

EDIT: As a workaround if downgraded to 7.2.5 for now.

EDIT 2: Downloading Z-Perl directly from GitHub gives you all the Files for 7.2.6. So it an issue with missing Files on the CurseForge side of things. Still can't use custom Spells for Range detection but the rest kind of works.

**Comment by mechanix4488** [comment]
How do you download from Github?

**Comment by Resike** [comment]
I manually pushed a new version to curse, their packager seems to have some issues,

**Comment by mechanix4488** [comment]
You are officially my new hero.  It's working again.  Thank you.
