### ISSUE TITLE
"TWW" New up date Borked all UI

### ISSUE THREAD

**Issue by Dreamindman** [Resike/Z-Perl#168]
All unit frames are greyed and unusable. one of the error messages after clicking minimap button:

Message: [string "*ZPerl.xml:74_OnClick"]:2: attempt to call global 'XPerl_MinimapButton_OnClick' (a nil value)
Time: Tue Aug 13 18:08:49 2024
Count: 1
Stack: [string "*ZPerl.xml:74_OnClick"]:2: attempt to call global 'XPerl_MinimapButton_OnClick' (a nil value)
[string "=[C]"]: in function `XPerl_MinimapButton_OnClick'
[string "*ZPerl.xml:74_OnClick"]:2: in function <[string "*ZPerl.xml:74_OnClick"]:1>
[string "=[C]"]: in function `Click'
[string "@Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua"]:5911: in function `OnClick'
[string "@Interface/AddOns/Decursive/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:179: in function <...ddOns/Decursive/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:177>

**Comment by Bamahutt** [comment]
Have the same issue, I have different errors:
5x [string "*ZPerl_Target.xml:38_OnLoad"]:6: attempt to call global 'ZPerl_Unit_OnEnter' (a nil value)
[string "*ZPerl_Target.xml:38_OnLoad"]:6: in function <[string "*ZPerl_Target.xml:38_OnLoad"]:5>

Locals:
self = XPerl_FocusnameFrame {
 Center = Texture { }
 RightEdge = Texture { }
 backdropInfo = <table> { }
 BottomEdge = Texture { }
 BottomLeftCorner = Texture { }
 BottomRightCorner = Texture { }
 TopEdge = Texture { }
 TopRightCorner = Texture { }
 TopLeftCorner = Texture { }
 LeftEdge = Texture { }
}
(*temporary) = nil
(*temporary) = XPerl_Focus { }
(*temporary) = "attempt to call global 'ZPerl_Unit_OnEnter' (a nil value)"
-----
5x [string "*ZPerl_Target.xml:38_OnLoad"]:9: attempt to call global 'ZPerl_Unit_OnLeave' (a nil value)
[string "*ZPerl_Target.xml:38_OnLoad"]:9: in function <[string "*ZPerl_Target.xml:38_OnLoad"]:8>

Locals:
self = XPerl_FocusnameFrame {
 Center = Texture { }
 RightEdge = Texture { }
 backdropInfo = <table> { }
 BottomEdge = Texture { }
 BottomLeftCorner = Texture { }
 BottomRightCorner = Texture { }
 TopEdge = Texture { }
 TopRightCorner = Texture { }
 TopLeftCorner = Texture { }
 LeftEdge = Texture { }
}
(*temporary) = nil
(*temporary) = XPerl_Focus {
}
(*temporary) = "attempt to call global 'ZPerl_Unit_OnLeave' (a nil value)"

**Comment by Kithhurrn** [comment]
Same. Unable to even get options to open, frames greyed out and a lot of everchanging error msgs.

**Comment by jbauerrfid** [comment]
Can confirm, all unit frames are completely grey without any content, since WoW build 11.0.2.56110
