### ISSUE TITLE
Lua Error - LibHealComm-4.0

### ISSUE THREAD

**Issue by boktai1000** [Resike/Z-Perl#17]
64x ...ddOns\ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0-94.lua:2176: table index is nil
[string "@ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0-94.lua"]:2176: in function `?'
[string "@ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0-94.lua"]:2801: in function <...ddOns\ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2799>

Locals:
self = <table> {
 TargetLastTarget = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2498
 GetHealModifier = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:377
 bucketFrame = <unnamed> {
 }
 TargetLastFriend = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2494
 compressGUID = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2328
 GetNextHealAmount = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:400
 ALL_HEALS = 23
 UseAction = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2503
 itemSetsData = <table> {
 }
 currentModifiers = <table> {
 }
 aurasUpdated = true
 tooltip = <unnamed> {
 }
 GetCasterHealAmount = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:520
 CASTED_HEALS = 3
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2406
 BOMB_HEALS = 16
 GetNumHeals = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:639
 callbacks = <table> {
 }
 removeRecordList = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:271
 getRecord = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:234
 UNIT_SPELLCAST_DELAYED = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2406
 Target = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2457
 GetOthersHealAmount = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:507
 UNIT_AURA = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1627
 tableCache = <table> {
 }
 GetPlayerHealingMod = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:372
 UPDATE_MOUSEOVER_UNIT = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2435
 ZONE_CHANGED_NEW_AREA = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1606
 healingModifiers = <table> {
 }
 hotMonitor = <unnamed> {
 }
 spellData = <table> {
 }
 guidToUnit = <table> {
 }
 CHARACTER_POINTS_CHANGED = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1727
 CastSpell = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2503
 DeleteTable = <function> defined @Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:192
 TargetUnit = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2457
 OnInitialize = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2690
 PLAYER_ENTERING_WORLD = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1601
 equippedSetCache = <table> {
 }
 unitToPet = <table> {
 }
 talentData = <table> {
 }
 PLAYER_EQUIPMENT_CHANGED = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1741
 ABSORB_SHIELDS = 8
 CastSpellByID = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2503
 CHANNEL_HEALS = 2
 CHAT_MSG_ADDON = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2048
 UNIT_SPELLCAST_SUCCEEDED = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2365
 guidToGroup = <table> {
 }
 UNIT_SPELLCAST_SENT = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2297
 tempPlayerList = <table> {
 }
 RegisterCallback = <function> defined @AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetHealAmount = <function> defined @ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:491
 RetrieveTable = <function> defined @Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:188
[zperl Healcomm Lua.txt](https://github.com/Resike/Z-Perl/files/7262268/zperl.Healcomm.Lua.txt)

**Comment by boktai1000** [comment]
I saw there was a recent Healcomm update in Z-Perl, but I actually received a new LUA error from that. I'm not sure if the issue I posted above is fixed, but I'm still getting LibHealComm LUA errors.

[211005-Zperl_LUA.txt](https://github.com/Resike/Z-Perl/files/7295399/211005-Zperl_LUA.txt)

**Comment by Resike** [comment]
What class/spec you play when this is triggered? And what's your game's text language?

**Comment by boktai1000** [comment]
BC Classic 2.5.2 (Phase 2)
Server - Pagle US East
Gnome Warrior (Alliance)
Spec if it matters is Fury Death Wish

Game's Text Language is English (US English if that matters - just whatever our default is in the states)

**Comment by Resike** [comment]
Is this still happening since that line should not throw that error `2176: table index is nil`, can you try to reinstall the addon if so?

**Comment by Zorziel** [comment]
Still happening on login and UI reload with newest version.  Reinstalled the addon and got the error, though mine is slightly different: `1146: table index is nil.`  

Z-Perl 6.2.9 Classic
WoW Classic 1.14.1.41243
Undead Priest


Here's the copy/paste of the error on my system:
> 
> Message: ...ddOns\ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1146: table index is nil
> Time: Sun Dec  5 02:19:28 2021
> Count: 1
> Stack: ...ddOns\ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1146: table index is nil
> [string "@Interface\AddOns\ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:1146: in function <...ddOns\ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1128>
> [string "@Interface\AddOns\ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:2726: in function `OnInitialize'
> [string "@Interface\AddOns\ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:2850: in function `?'
> [string "@Interface\AddOns\ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:2829: in function <...ddOns\ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2825>
> 
> Locals: Renew = "Renew"
> GreaterHeal = "Greater Heal"
> PrayerofHealing = "Prayer of Healing"
> FlashHeal = "Flash Heal"
> Heal = "Heal"
> LesserHeal = "Lesser Heal"
> SpiritualHealing = "Spiritual Healing"
> ImprovedRenew = "Improved Renew"
> GreaterHealHot = "Greater Heal"
> CureDisease = "Cure Disease"
> BindingHeal = "Binding Heal"
> EmpoweredHealing = "Empowered Healing"
> Renewal = nil
> (*temporary) = <table> {
>  Renew = <table> {
>  }
>  Greater Heal = <table> {
>  }
> }
> (*temporary) = <table> {
>  levels = <table> {
>  }
>  coeff = 0
>  interval = 3
>  ticks = 3
>  averages = <table> {
>  }
> }
> (*temporary) = <table> {
>  1 = 150
> }
> (*temporary) = 150
> (*temporary) = 100
> (*temporary) = 175
> (*temporary) = 245
> (*temporary) = 315
> (*temporary) = 400
> (*temporary) = 510
> (*temporary) = 650
> (*temporary) = 810
> (*temporary) = 970
> (*temporary) = 1010
> (*temporary) = 1110
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "table index is nil"
> GetSpellInfo = <function> defined =[C]:-1
> hotData = <table> {
>  Renew = <table> {
>  }
>  Greater Heal = <table> {
>  }
> }
> spellData = <table> {
> }
> avg = <function> defined @Interface\AddOns\ZPerl\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:720
> isTBC = false
> talentData = <table> {
> }
> itemSetsData = <table> {
> }
> GetHealTargets = nil
> playerGUID = "Player-5131-011F22A3"
> compressGUID = <table> {
> }
> UnitGUID = <function> defined =[C]:-1
> guidToGroup = <table> {
> }
> pairs = <function> defined =[C]:-1
> guidToUnit = <table> {
>  Player-5131-011F22A3 = "player"
> }
> IsSpellInRange = <function> defined =[C]:-1
> CheckInteractDistance = <function> defined =[C]:-1
> CalculateHotHealing = nil
> SpellIDToRank = <table> {
>  27030 = 11
>  139 = 1
>  9473 = 3
>  27046 = 8
>  3472 = 6
>  19942 = 5
>  9750 = 6
>  9758 = 8
>  746 = 1
>  1042 = 5
>  23568 = 8
>  25357 = 10
>  939 = 5
>  1430 = 3
>  24413 = 8
>  10838 = 7
>  26979 = 13
>  26983 = 5
>  5185 = 1
>  5186 = 2
>  5187 = 3
>  5188 = 4
>  5189 = 5
>  25222 = 12
>  9840 = 9
>  18608 = 9
>  27031 = 12
>  3627 = 6
>  9856 = 7
>  9858 = 9
>  9862 = 3
>  8008 = 2
>  8010 = 3
>  19939 = 2
>  689 = 1
>  25314 = 5
>  10396 = 9
>  9888 = 9
>  913 = 4
>  10916 = 6
>  1058 = 2
>  27135 = 10
>  23569 = 6
>  10928 = 8
>  11695 = 7
>  755 = 1
>  11699 = 5
>  596 = 1
>  331 = 1
>  8910 = 7
>  8918 = 2
>  10960 = 3
>  30020 = 11
>  27219 = 7
>  1064 = 1
>  3268 = 4
>  26980 = 10
>  332 = 2
>  10466 = 4
>  8938 = 2
>  8940 = 4
>  27259 = 8
>  25235 = 9
>  13544 = 7
>  9472 = 2
>  9474 = 4
>  3661 = 3
>  3662 = 4
>  19940 = 3
>  25299 = 11
>  25315 = 10
>  27136 = 11
>  635 = 1
>  699 = 2
>  26981 = 12
>  25221 = 11
>  136 = 1
>  25297 = 11
>  8005 = 7
>  996 = 2
>  25391 = 11
>  8004 = 1
>  6063 = 3
>  6064 = 4
>  25210 = 6
>  24412 = 6
>  7927 = 6
>  11700 = 6
>  25423 = 5
>  11694 = 6
>  774 = 1
>  27220 = 8
>  10839 = 8
>  6074 = 2
>  6075 = 3
>  6076 = 4
>  6077 = 5
>  6078 = 6
>  10468 = 6
>  25213 = 7
>  19943 = 6
>  6778 = 6
>  9839 = 8
>  9841 = 10
>  3267 = 3
>  709 = 3
>  18610 = 10
>  10917 = 7
>  25233 = 8
>  10623 = 3
>  11693 = 5
>  10622 = 2
>  10964 = 3
>  959 = 6
>  9863 = 4
>  10328 = 7
>  23567 = 10
>  24414 = 10
>  639 = 2
>  25292 = 9
>  19941 = 4
>  1159 = 2
>  25422 = 4
>  25308 = 6
>  3698 = 2
>  25316 = 5
>  3699 = 3
>  9889 = 10
>  3700 = 4
>  9857 = 8
>  10915 = 5
>  1026 = 4
>  547 = 3
>  37563 = 1
>  27137 = 7
>  13542 = 5
>  19750 = 1
>  10929 = 9
>  32546 = 1
>  22009 = 5
>  7651 = 4
>  2054 = 1
>  2055 = 2
>  2050 = 1
>  8903 = 7
>  25396 = 12
>  740 = 1
>  2052 = 2
>  2090 = 4
>  2053 = 3
>  2091 = 5
>  25420 = 7
>  10395 = 8
>  10961 = 4

**Comment by boktai1000** [comment]
Apologies on the delay on my follow up here, but I do believe it's still happening. I've been recording events with BugSack/BugGrabber and here's an example

[220126-zperl-lua.txt](https://github.com/Resike/Z-Perl/files/7943915/220126-zperl-lua.txt)

**Comment by Resike** [comment]
Should be fixed with the next version.
