### ISSUE TITLE
Target's buffs not showing at all (Classic-SoD)

### ISSUE THREAD

**Issue by Zwyk** [Resike/Z-Perl#176]
Target's buffs are not showing at all since last update on Classic-SoD, neither for friends nor ennemies. 
Target's debuffs are working as intended.
Target's target's (and other frames) buffs and debuffs are working as intended.

No errors showing.

**Comment by Fieora** [comment]
Having the same issue, interestingly target of target buffs are working

**Comment by Fieora** [comment]
https://github.com/Resike/Z-Perl/blob/67c99e84007ba860760006f38b58863aaab81f91/ZPerl/ZPerl.lua#L2683

is responsible, I'm not sure what the changes were targeting

**Comment by cars11** [comment]
the buffs are back, but you can't see a tooltip on them if you hover?

**Comment by Zwyk** [comment]
> the buffs are back, but you can't see a tooltip on them if you hover?

Yeah, should maybe open another ticket for that
