### ISSUE TITLE
Opening Map with 3D Portrait freezes the game

### ISSUE THREAD

**Issue by chudabega** [Resike/Z-Perl#181]
In the Player (tab) > Player Portrait > 3D Portrait

If I have that option enabled and I open my map, the game will freeze indefinitely. Disabling it stops the issue from happening.
It's not throwing an error as far as I can tell, I assume it's entering an infinite loop.
If I hit escape or m and close the map, the game will start running again a few seconds later.

The issue seems to potentially be intermittent, but it is consistently happening all the time on one of my characters today.

I had the issue happen on other characters and when investigating by disabling all addons and re-enabling them the issue disappeared.

I am on an undead rogue in the Valley of Strength in Orgrimmar when the freeze is occurring.

**Comment by Resike** [comment]
It's most likely an issue with the model file that could be your character or any piece of gear your character using or any buff that changes the model of your character. Usually recently added/changed models can cause this issue. You could try to reinstall the game or use the `scan and repair` tool, if that not gonna fix it you need to report the issue to Blizzard with a detailed info included from the GPU you are using.

**Comment by chudabega** [comment]
Thanks, it appears to be some issue with the Cache folder. It seems to be resolved after deleting it.
Other addons that were showing models or if I had my character window open and attempted to open the map would also cause the issue.
