### ISSUE TITLE
zPerl bugging out water effects in wow classic

### ISSUE THREAD

**Issue by cokesplash** [Resike/Z-Perl#188]
zPerl is bugging out water effects in-game. When "Liquid Detail" under "Graphics settings" are set to "Good" or "High", the water edges flicker constantly.  When Zperl is disabled, the flickering effect stops.

**Comment by cokesplash** [comment]
I have narrowed the problem down to the 3D player portrait. If you uncheck 3D portrait on the player tab, the water issues immediately stop.

**Comment by Resike** [comment]
Are you on MAC?
Have you tried to exit the game and delete your `World of Warcraft\WOWFLAVOR\Cache` folder?

**Comment by cokesplash** [comment]
I'm on windows. I deleted the cache folder (playing classic era) and it had no effect on the bug.

**Comment by Resike** [comment]
Yeah you gonna have to report this issue to Blizzard then, including your DirectX and OS info.

**Comment by cokesplash** [comment]
I have 3 computers all with different graphics cards that are all having the same issue with zPerl and many others in my guild are having the same problem. What makes you think this is a Blizzard problem? Considering when I disable the 3D portrait in zperl, I can tell you exactly what they will say if I report it to them.

**Comment by Fieora** [comment]
> I have 3 computers all with different graphics cards that are all having the same issue with zPerl and many others in my guild are having the same problem. What makes you think this is a Blizzard problem? Considering when I disable the 3D portrait in zperl, I can tell you exactly what they will say if I report it to them.

While it may be Zperl interacting with the render pipeline causing the issue, it doesn't mean it's a problem with what Zperl is doing. An addon can't interact with textures or objects in the 3D world, only the interface layer. So if loading a 3d model in the interface layer causes this behavior, it points to a problem in the render pipeline in WOW, not the addon. 

If I remember correctly this started after the sunken temple phase started (before Zperl updated), If I had to guess, they were experimenting with some new glow or particle effects and never caught this problem.

**Comment by cokesplash** [comment]
Just a heads up that this has been fixed in the latest patch! So you were right :)
