### ISSUE TITLE
Configure Z-Perl on GitHub so that it works with WowUp

### ISSUE THREAD

**Issue by Xerus2** [Resike/Z-Perl#19]
Apologies if this was already asked, but I wanted to see if it's possible to configure Z-Perl so that it can be updated via GitHub by WowUp. I am not sure of the exact changes which need to be made for this, I found: https://wowup.io/guide/wowup/hub and a sample configuration at https://github.com/WowUp/WowUp.Addon. There's also a WowUp discord server where the devs are available for questions and help: https://discord.gg/rk4F5aD.

**Comment by Xerus2** [comment]
Looked at this a little more; I think you need to convert Z-Perl into a single release package with multiple TOC files, instead of a separate release package for each flavor of WoW.

**Comment by austen0** [comment]
I'd also appreciate this. The [BigWigs releaser](https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow) will create releases compatible with WoWUp.

**Comment by Zetaprime82** [comment]
This would be awesome if this happend

**Comment by Ethan-BB** [comment]
This would be greatly appreciated.

**Comment by newdamage1** [comment]
I also would like for this to happen! TY!

**Comment by YoanKECH** [comment]
+1 ! :)

**Comment by YoanKECH** [comment]
bump ! ^^

**Comment by vjtd3** [comment]
This would be very much appreciated. Hoping Z-Perl is able to be updated on Wowup either via GitHub or mirrored on Wago or something.

**Comment by ForsakenNGS** [comment]
+1

**Comment by vjtd3** [comment]
Is there any chance of this happening?

**Comment by Resike** [comment]
Nope. WowUp properly supports Curse mods now:
[https://github.com/WowUp/WowUp.CF](https://github.com/WowUp/WowUp.CF)
