### ISSUE TITLE
Zperl Wrath acting not regularly after the update

### ISSUE THREAD

**Issue by Mallyvolent** [Resike/Z-Perl#25]
Hi there, 
![WowClassic_2022-09-03_21-41-33](https://user-images.githubusercontent.com/112793115/188297799-38c4e73d-3fec-4a46-9fe7-0902c4bd70a9.jpg)

After wrath update, the frames look weird with targets not clearing on click. Focus is always up.

**Comment by Resike** [comment]
You must get some kinda error gonna need to see that.
