### ISSUE TITLE
Possible to Backport Z-Perl to 3.3.5?

### ISSUE THREAD

**Issue by Esparanta** [Resike/Z-Perl#31]
Hey, a long time X-Perl user here. I realized of your ambitious work, improvising X-Perl and naming into Z-Perl. While you update to current WoW versions for your addon, would you like to also update Vanilla-TBC-WOTLK (1.12.1-2.4.3-3.3.5) variants? Especially 3.3.5 would be sweet since WOTLK is popular atm. It will be also a good nod or tribute to former addon X-Perl, if you do that.

**Comment by PatricNox** [comment]
https://github.com/Resike/Z-Perl/releases/tag/6.3.4-Wrath

**Comment by Esparanta** [comment]
I'm not asking for Classic version, mind you. Thanks for sharing regardless.

**Comment by PatricNox** [comment]
> I'm not asking for Classic version, mind you. Thanks for sharing regardless.

I don't understand, how can the classic version not work for your 3.3.5a client?

**Comment by Esparanta** [comment]
Because WOTLK classic (w/e version) and WOTLK 3.3.5 have different infrastructures. It's more like you are offering me lemons while i was asking for oranges, let's say: They have quite similar looks yet different within. Feel free to try on Warmane or ChromieCraft if you don't believe me, either states "out of date" while it should be "updated to 3.3.5". Guess it's clear now

**Comment by Zetaprime82** [comment]
if you want to use a 3.3.5 version you have to look in to the original project that was named X-Perl
https://www.wowace.com/projects/xperl/files/825399 <--- link to a 3.3.5 original wotlk version

**Comment by Esparanta** [comment]
> if you want to use a 3.3.5...

Ever read of my original post? I already KNOW that XPerl EXISTS in 3.3.5 because I said "I'm a long time X-Perl user". I am literally demanding an UPDATE to XPerl to old versions or a backport of ZPerl, whatever you like to call it. How you can't comprehend of whole point of this post baffles me.

**Comment by Zetaprime82** [comment]
Yeah..... i higly doubt Resike wil ever make Z-perl to work on a 1.12.1-2.4.3-3.3.5 private wow server :P

**Comment by Resike** [comment]
Yeah I have no access to these private clients neither have time to backport, so I don't think it's gonna happen.
Your best bet is just to keep using X-Perl.
