### ISSUE TITLE
Hide CompactRaidFrameManager

### ISSUE THREAD

**Issue by wlfbck** [Resike/Z-Perl#35]
Title pretty much - other raidframe addons simply do that. And it would be neat if Z-Perl also had atleast an option to do just that, since that menu is completely useless, but still takes up space even when shrunk.

Talking about [this](https://i.redd.it/95xfrigzpdm91.png) ofcourse.

**Comment by Resike** [comment]
I don't think that's a good idea, that's the only way to set world marker targets while in combat.

**Comment by wlfbck** [comment]
You can assign them via rightclicking as well as hotkeys.

**Comment by Resike** [comment]
But not the world markers that you place on the ground.
I could add an extra option to hide it later.

**Comment by wlfbck** [comment]
Ah okay, those do not exist in classic. So there blizzards sidemenu does nothing :)
