### ISSUE TITLE
#wotlkclassic Ulduar / phase 2 PTR Errors

### ISSUE THREAD

**Issue by vjtd3** [Resike/Z-Perl#37]
Raid frames completely non-functional (each frame displays ERROR and does not update on status changes), strange white coloring on unit frames, "pet target" frame is stuck on even without a pet active, settings window has a blinding white background and can not be moved. Only addons enabled are Z-Perl and Swatter. Errors linked below in pastebin.

https://pastebin.com/RSXRn1tD
https://pastebin.com/iChDyEwR
https://pastebin.com/4DVhP1Xx
https://pastebin.com/0A218itK
https://pastebin.com/9507BMyX

Some screenshot examples from during our PTR raids:

Raid frames: 
![image](https://user-images.githubusercontent.com/16548201/207800779-40bb7a72-e8fb-4df7-9aa5-346f28f66509.png)

White on player frame (does not always do this for some reason):
![image](https://user-images.githubusercontent.com/16548201/207800874-0ca7fae9-9f4c-4f08-8916-3f815b220a42.png)

The strange stuck "pet target" frame, which appears to have the health bar updated sometimes but I couldn't figure out what was changing it:
![image](https://user-images.githubusercontent.com/16548201/207801022-6399eb59-4e1f-46e6-b4d4-49feae781aa9.png)

Target of target frame:
![image](https://user-images.githubusercontent.com/16548201/207801712-de5b2c8b-458d-4045-84a0-7f974cf67b0f.png)

Settings window (warning: blinding white):
https://i.imgur.com/uw1lDcp.png

This is what the player frame looks like on a fresh character with all modules enabled and settings copied from the "main." 
![image](https://user-images.githubusercontent.com/16548201/207802292-bdc3ff9a-f819-4820-b0d4-48a2d58b0769.png)
Doesn't look the same as on my "main."
![image](https://user-images.githubusercontent.com/16548201/207802866-c33e7430-bbbd-4819-a19b-90f8f91a0dba.png)

**Comment by vjtd3** [comment]
With PTR back up I was finally able to test in a raid group. Was actually in the middle of raid when this update was posted. Looks like all of the same bugs are here, most of the errors are the same except for one of them.

Full UI screenshot:
![image](https://user-images.githubusercontent.com/16548201/211121278-4b6bdf84-02cd-4b3f-ba14-4385180facd2.png)

Error #1: https://pastebin.com/5gmPxLj7 (no change)
Error #2: https://pastebin.com/QzyuG3RY (no change)
Error #3: https://pastebin.com/YBmBk2vK (something different on line #134 of the paste)
Error #4: https://pastebin.com/cuPMHUCM (no change)
Error #5: https://pastebin.com/hbi8zxnw (no change)
Error #6: https://pastebin.com/WLJ3g4VD (new error ZPerl_PlayerPet.lua)

**Comment by Resike** [comment]
It's gonna be fixed with the next release.
