### ISSUE TITLE
#wotlkclassic Ulduar & phase 2, updated errors

### ISSUE THREAD

**Issue by vjtd3** [Resike/Z-Perl#39]
Referencing #37 

With PTR back up I was finally able to test in a raid group. Was actually in the middle of raid when this update was posted. Looks like all of the same bugs are here, most of the errors are the same except for one of them.

Full UI screenshot:
![image](https://user-images.githubusercontent.com/16548201/211121278-4b6bdf84-02cd-4b3f-ba14-4385180facd2.png)

Rest of the config UI is the same blinding white and not moveable:
![image](https://user-images.githubusercontent.com/16548201/211122435-bb5d4231-ce65-4a1d-ba44-03f0fea7e57f.png)

Error 1: https://pastebin.com/5gmPxLj7 (no change)
Error 2: https://pastebin.com/QzyuG3RY (no change)
Error 3: https://pastebin.com/YBmBk2vK (something different on line #134 of the paste)
Error 4: https://pastebin.com/cuPMHUCM (no change)
Error 5: https://pastebin.com/hbi8zxnw (no change)
Error 6: https://pastebin.com/WLJ3g4VD (new error ZPerl_PlayerPet.lua)

**OLD list of errors to make comparing to the above easier**, though most of them were the same:
https://pastebin.com/RSXRn1tD
https://pastebin.com/iChDyEwR
https://pastebin.com/4DVhP1Xx
https://pastebin.com/0A218itK
https://pastebin.com/9507BMyX

**Comment by Resike** [comment]
It's gonna be fixed with the next release.

**Comment by vjtd3** [comment]
Apologies, I misunderstood the "completed" as being what was uploaded at about the same time and wanted to help since I was in a good position to do so in raid.
