### ISSUE TITLE
Not registering event on focustarget [BCC]

### ISSUE THREAD

**Issue by corporategoth** [Resike/Z-Perl#4]
When you made the change to add BCC support, you changed the Focus frame event registration as follows:

ZPerl_Target.lua:
```
                if not IsVanillaClassic then
                        self:RegisterEvent("PLAYER_FOCUS_CHANGED")
                end
```

However you neglected to make the same change for Focus's Target, it still shows:

ZPerl_TargetTarget.lua:
```
                if not IsClassic then
                        self:RegisterEvent("PLAYER_FOCUS_CHANGED")
                end
```

You should using the same condition for focus target as for focus to register the frame event handling.

**Comment by Resike** [comment]
Fixed
