### ISSUE TITLE
Totem bar not showing

### ISSUE THREAD

**Issue by ThiefMaster** [Resike/Z-Perl#40]
Basically this: https://www.curseforge.com/wow/addons/zperl/issues/410
Any chance it could get fixed?

**Comment by Resike** [comment]
With the next version. SoonTM.

**Comment by ThiefMaster** [comment]
@Resike 4 months later... any chance for a fix? :)
Or at least a pointer on what I need to comment out in the code to get the Blizzard totem bar?
