### ISSUE TITLE
LibClassicCasterino will never work on anything but classic era

### ISSUE THREAD

**Issue by corporategoth** [Resike/Z-Perl#5]
Because the initial check at the top of LibClassicCasterino.lua still has:

```
if WOW_PROJECT_ID ~= WOW_PROJECT_CLASSIC then return end
```

Then this library will be completely disabled in, say, classic TBC.
So the code you added to check API levels is useless, because in classic TBC, the library will never load it's contents.

The above check needs to be modified to something like:

```
if WOW_PROJECT_ID == WOW_PROJECT_MAINLINE then return end
```

**Comment by corporategoth** [comment]
FYI, the same applies to LibClassicDurations (though I'm not sure if, in this case, this is intended, as it seems you're explicitly excluding that library for TBC.  Is it no longer necessary with TBC?)

**Comment by Resike** [comment]
Why should they be enabled doesn't BCC have proper casting events and buff/debuff durations?

**Comment by corporategoth** [comment]
I don't know - it's possible they might NOT be necessary in BCC - however at least LibClassicCasterino has some explicit changes for BCC, so presumably it's still needed?

I've not checked to see if LibClassicDurations is still required.  I would have to see a buff/debuff on someone else and ensure that I can see the time remaining (which I believe is what it does).

**Comment by Resike** [comment]
I've tested it and it seems to work without the library enabled on BCC.
