### ISSUE TITLE
Blizzard Frames can't be used

### ISSUE THREAD

**Issue by Rivertrent** [Resike/Z-Perl#50]
the tab for Blizzard frames is gone, the only thing there is the Hide button. I like using z-perl frames but I like to use the blizzard frames for raid. I stop using z-perl and it works. I tried unchecking raid frames, party frames. I tried uninstalling z-perl. Can not get the tab to open. I've even when into Blizzard interface to the show raid frames and nothing. anyone else having this issue?

**Comment by Resike** [comment]
Raid settings -> Uncheck Disable the default raid frames
