### ISSUE TITLE
Player frame stays big after shape shift

### ISSUE THREAD

**Issue by corporategoth** [Resike/Z-Perl#6]
If I'm on my druid, and I shape shift, say into cat form, the player frame looks normal:
![WoWScrnShot_052021_180940](https://user-images.githubusercontent.com/3732622/119063746-d5a57700-b9a7-11eb-95da-d69da2939ffd.jpg)

However, when I shift OUT of cat form again, the player frame stays too big, and the health portion is too big:
![WoWScrnShot_052021_180944](https://user-images.githubusercontent.com/3732622/119063764-e6ee8380-b9a7-11eb-9daf-1c15ddd61fe6.jpg)

On initial login, not in shape shift form, the health portion of the frame is normal sized.

**Comment by Resike** [comment]
Should be fixed with the next release.
