### ISSUE TITLE
Player and target frames showing Picture on right hand side when in Moonkin form

### ISSUE THREAD

**Issue by Ifartstarz** [Resike/Z-Perl#72]
Like the title says, when I am in Moonkin form, or any form, it shows a picture on the right depicting my form. How do I get rid of of this? It even shows a picture when I eat. It doesnt do this on my other characters, only the boomkin.   Here's a SS of what I mean: 
![WoWScrnShot_071923_165932](https://github.com/Resike/Z-Perl/assets/112528341/292831d7-b314-4e56-a185-46e11ea719f7)

**Comment by Resike** [comment]
I think that is a different addon doing this.
