### ISSUE TITLE
localization.zhTW

### ISSUE THREAD

**Issue by Iambookz** [Resike/Z-Perl#80]
2x ZPerl_Options/localization.zhTW.lua:831: attempt to concatenate a nil value
[string "@ZPerl_Options/localization.zhTW.lua"]:831: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@ZPerl/ZPerl_Globals.lua"]:669: in function `XPerl_LoadOptions'
[string "@ZPerl/ZPerl_Globals.lua"]:699: in function <ZPerl/ZPerl_Globals.lua:698>
[string "=[C]"]: ?
[string "@ZPerl/ZPerl_Init.lua"]:201: in function `XPerl_pcall'
[string "@ZPerl/ZPerl_Globals.lua"]:492: in function <ZPerl/ZPerl_Globals.lua:474>
[string "@ZPerl/ZPerl_Globals.lua"]:617: in function <ZPerl/ZPerl_Globals.lua:591>

Locals:
IsClassic = true
(*temporary) = "啟用"
(*temporary) = nil

**Comment by Resike** [comment]
Gonna be fixed with next version.
