### ISSUE TITLE
LUA error when loading into the game

### ISSUE THREAD

**Issue by Aenimma** [Resike/Z-Perl#86]
I get this error each time I load into the game

Date: 2023-10-14 17:47:45
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/ZPerl_Target/ZPerl_Target.lua line 1544:
   attempt to call global 'UnitIsBattlePet' (a nil value)
Debug:
   [string "@Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua"]:146:
      ...tCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:144
   [string "=[C]"]: UnitIsBattlePet()
   [string "@Interface/AddOns/ZPerl_Target/ZPerl_Target.lua"]:1544: func()
   [string "@Interface/AddOns/ZPerl_Target/ZPerl_Target.lua"]:1301:
      Interface/AddOns/ZPerl_Target/ZPerl_Target.lua:1299
Locals:
private = <table> {
 ThrowError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:77
 NewError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface/AddOns/Decursive/Dcr_DIAG.lua:637

**Comment by Resike** [comment]
Fixed with next release.
