### ISSUE TITLE
resto shaman, curse debuff highlight not showing 

### ISSUE THREAD

**Issue by Bozzeu** [Resike/Z-Perl#88]
for my shaman the raid player frame does not highlight in Purple when the target is affected by a removable curse debuff. 
does anyone knows how to fix this?

thanks!

**Comment by Resike** [comment]
Which client?

**Comment by Bozzeu** [comment]
Classic WOTLK. so just to be clear the frame of the player that has a curse on them doesn't highlight in purple, like on the druid / mage.

**Comment by Resike** [comment]
Fixed with next release.

**Comment by Bozzeu** [comment]
Great, thanks!
