### ISSUE TITLE
Buffs/Debuffs Not Showing Their Icon Timers

### ISSUE THREAD

**Issue by Jackodawacko** [Resike/Z-Perl#9]
Hi there,

The buff/debuff icons are staying solid the whole time and not going darker (in clockwise) as the buff/debuff is ticking away per second. With the default Blizzard UI, you can see that the buff/debuff is ticking down (and getting darker) so you know when the buff/debuff is about to end.

Here is a video I created that shows (with commentary) what it happening on the Blizzard UI vs Z-Perl: https://streamable.com/j5zzsq

Let me know if you need any more information/more suggestions.

Thank you!

**Comment by Jackodawacko** [comment]
@Resike forgot to tag you again :D

**Comment by Macumbatbc** [comment]
+1 here some screen

Default UI

![unknown-332](https://user-images.githubusercontent.com/85767653/121773839-fe6ff500-cb7e-11eb-988a-8fedf281710c.png)


With Zperl
![unknown-291](https://user-images.githubusercontent.com/85767653/121773861-15164c00-cb7f-11eb-852b-368f773b073a.png)

As a reminder you can have the same issue with default frames if the buffs/debuff are too small. 
So increase the frame which increase the buffs also fix it.
That's not the case with Zperl

**Comment by Resike** [comment]
You guys need to enable this:
![image](https://user-images.githubusercontent.com/3955703/122121447-f4bee980-ce2b-11eb-8d5b-356ec32b7758.png)

**Comment by Macumbatbc** [comment]
I'll give it a try.
Thanks

**Comment by Jackodawacko** [comment]
Thank you! Will marked this closed
