### ISSUE TITLE
blizzard api block error

### ISSUE THREAD

**Issue by Ssesmar** [Resike/Z-Perl#95]
27x [ADDON_ACTION_BLOCKED] AddOn 'ZPerl_Target' hat versucht die geschützte Funktion 'CheckInteractDistance()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: ?
[string "@ZPerl_Target/ZPerl_Target.lua"]:748: in function <ZPerl_Target/ZPerl_Target.lua:706>
[string "@ZPerl_Target/ZPerl_Target.lua"]:822: in function <ZPerl_Target/ZPerl_Target.lua:768>
[string "@ZPerl_Target/ZPerl_Target.lua"]:1225: in function `XPerl_Target_UpdateDisplay'
[string "@ZPerl_Target/ZPerl_Target.lua"]:1491: in function `func'
[string "@ZPerl_Target/ZPerl_Target.lua"]:1317: in function <ZPerl_Target/ZPerl_Target.lua:1315>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by Xerus2** [comment]
Similar issue:

Message: [ADDON_ACTION_BLOCKED] AddOn 'ZPerl' tried to call the protected function 'IsItemInRange()'.
Time: Sat Nov 18 09:39:43 2023
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'ZPerl' tried to call the protected function 'IsItemInRange()'.
[string "@Interface/AddOns/ZPerl/ZPerl.lua"]:556: in function `XPerl_UpdateSpellRange'
[string "@Interface/AddOns/ZPerl_TargetTarget/ZPerl_TargetTarget.lua"]:351: in function `XPerl_TargetTarget_UpdateDisplay'
[string "@Interface/AddOns/ZPerl_TargetTarget/ZPerl_TargetTarget.lua"]:516: in function <...ace/AddOns/ZPerl_TargetTarget/ZPerl_TargetTarget.lua:504>

Locals: self = XPerl_TargetTarget {
 0 = <userdata>
 perlBuffs = 6
 targetmanamax = 100
 guid = "Player-3676-08AE850A"
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 buffSetup = <table> {
 }
 targethp = 481900
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 VSPACING = -1
 targethpmax = 481900
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 buffOptMix = "6000010"
 prevBuff = XPerlBuff5 {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 BOTTOMRIGHT = "BOTTOMRIGHT"
 highlight = XPerl_TargetTargethighlight {
 }
 buffSpacing = <table> {
 }
 lastUpdate = 219372.194000
 afk = false
 BOTTOMLEFT = "BOTTOMLEFT"
 TOPRIGHT = "TOPRIGHT"
 nameFrame = XPerl_TargetTargetnameFrame {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SPACING = 1
 buffFrame = XPerl_TargetTargetbuffFrame {
 }
 statsFrame = XPerl_TargetTargetstatsFrame {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 conf = <table> {
 }
 targetmanatype = 13
 TOPLEFT = "TOPLEFT"
 perlDebuffs = 0
 targetmana = 6
 partyid = "targettarget"
 debuffFrame = XPerl_TargetTargetdebuffFrame {
 }
 parentid = "target"
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 targetname = "Xerus"
 levelFrame = XPerl_TargetTargetlevelFrame {
 }
}
overrideUnit = "targettarget"
isRaidFrame = nil
unit = "targettarget"
rf = <table> {
 StatsFrame = <table> {
 }
 enabled = true
 Main = <table> {
 }
 NameFrame = <table> {
 }
}
mainA = nil
nameA = nil
statsA = nil
SecureButton_GetUnit = <function> defined @Interface/FrameXML/SecureTemplates.lua:195
conf = <table> {
 showReadyCheck = 1
 highlight = <table> {
 }
 highlightSelection = 1
 rangeFinder = <table> {
 }
 showAFK = 1
 party = <table> {
 }
 buffHelper = <table> {
 }
 raidpet = <table> {
 }
 target = <table> {
 }
 raid = <table> {
 }
 optionsColour = <table> {
 }
 colour = <table> {
 }
 targettargettarget = <table> {
 }
 minimap = <table> {
 }
 focus = <table> {
 }
 pet = <table> {
 }
 highlightDebuffs = <table> {
 }
 tooltip = <table> {
 }
 pettarget = <table> {
 }
 partypet = <table> {
 }
 transparency = <table> {
 }
 player = <table> {
 }
 custom = <table> {
 }
 focustarget = <table> {
 }
 targettarget = <table> {
 }
 buffs = <table> {
 }
 maximumScale = 1.500000
 bar = <table> {
 }
}
UnitIsVisible = <function> defined =[C]:-1
DoRangeCheck = <function> defined @Interface/AddOns/ZPerl/ZPerl.lua:344
UnitIsConnected = <function> defined =[C]:-1

**Comment by Resike** [comment]
Fixed with next release.

**Comment by Resike** [comment]
Fixed with next release.
