### ISSUE TITLE
Can't see new party members until you are out of combat

### ISSUE THREAD

**Issue by zeenk** [Resike/Z-Perl#97]
Not sure if this is a bug or intended behaviour to avoid stuff from not working correctly but noticed today when I invited my alts while I was in combat their party frames didn't show up until I was out of combat again, if that is intended you can just close this issue but thought I could mention it to you atleast :P

**Comment by Resike** [comment]
It looks like Blizz messed something up, and the secure state handler doesn't seem to trigger for party frames in combat.

**Comment by zeenk** [comment]
Fixed in 7.2.1
